services:
  - type: web
    name: decided
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: "/api/health"
    envVars:
      - key: DATABASE_URL
        sync: false
        # fromDatabase:
        #   name: decided-db
        #   property: connectionString
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_HOST
        sync: false
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_ACCESS_TOKEN
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_HOST
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

    autoDeploy: true

# databases:
#   - name: decided-db
#     plan: free
#     postgresMajorVersion: 15

# previews:
#   generation: automatic
#   services:
#     - name: decided-preview
#       type: web
#       plan: starter
#       buildCommand: "npm install && npm run build"
#       startCommand: "npm start"
#       preDeployCommand: "npx drizzle-kit push"
#       envVars:
#         - key: DATABASE_URL
#           fromDatabase:
#             name: decided-db-preview
#             property: connectionString
#   databases:
#     - name: decided-db-preview
#       plan: starter
#       postgresMajorVersion: 15 